version: '3.8'

services:
  pg_container_focoanuncio:
    image: postgis/postgis:16-3.5
    #restart: always
    container_name: pg_container_focoanuncio
    environment:
      POSTGRES_DB: db_focoanuncio_tech
      POSTGRES_USER: leoneldev_tech
      POSTGRES_PASSWORD: leoneldev_tech@123
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: focoanuncio_backend
    restart: always
    env_file:
      - .development.env
    depends_on:
      pg_container_focoanuncio:
        condition: service_healthy
    ports:
      - '3002:3002' # o el puerto que uses
    volumes:
      - .:/app # Monta el directorio actual en /app
      - /app/node_modules # Evita sobrescribir node_modules
    environment:
      NODE_ENV: development
      DATABASE_HOST: pg_container_focoanuncio
      DATABASE_PORT: 5432
      DATABASE_USER: leoneldev_tech
      DATABASE_PASSWORD: leoneldev_tech@123
      DATABASE_NAME: db_focoanuncio_tech
    user: root
    command: pnpm run start:dev
volumes:
  pgdata:
